FROM node:20-alpine@sha256:fb4cd12c85ee03686f6af5362a0b0d56d50c58a04632e6c0fb8363f609372293 AS base
WORKDIR /app

COPY package*.json ./

FROM base AS dev
RUN npm ci
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]

FROM base AS build
RUN npm ci
COPY . .
ARG VITE_AUTH_API_BASE_URL=/api/auth
ENV VITE_AUTH_API_BASE_URL=${VITE_AUTH_API_BASE_URL}
ARG VITE_NODE_RED_BASE_URL=/nodered
ENV VITE_NODE_RED_BASE_URL=${VITE_NODE_RED_BASE_URL}
RUN npm run build

FROM nginx:1.27-alpine@sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10 AS prod
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80