FROM node:20-alpine@sha256:fb4cd12c85ee03686f6af5362a0b0d56d50c58a04632e6c0fb8363f609372293 AS base
WORKDIR /app

COPY package*.json ./

FROM base AS dev
RUN npm ci
COPY . .
EXPOSE 4000
CMD ["npm", "run", "server"]

FROM base AS prod
RUN npm ci --omit=dev
COPY . .
EXPOSE 4000
CMD ["npm", "run", "server"]