FROM node:20-alpine AS base
WORKDIR /app

COPY package*.json ./

FROM base AS dev
RUN npm ci
COPY . .
EXPOSE 4000
CMD ["npm", "run", "server"]

FROM base AS prod
RUN npm ci --omit=dev
COPY . .
EXPOSE 4000
CMD ["npm", "run", "server"]